services:
  jupyter-java:
    container_name: "jupyter-java"
    image: "quay.io/jupyter/minimal-notebook:latest"
    volumes:
      - "/srv/clases/Programacion/Java/apuntes:/home/jovyan/work"
    ports:
      - "10002:8888"

    # 'healthcheck' establece cual será el comando y cuales serán los tiempos para decir si un contenedor está sano, insano o ha fallado 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/"]
      interval: 10s
      timeout: 10s
      retries: 3
