version: "3.1"

services:
  mysql:
    container_name: "jupyter-python"
    image: "quay.io/jupyter/minimal-notebook:latest"
    volumes:
      - "/mnt/NAS/Clases/Programación/Python/Apuntes:/home/jovyan/work"
    environment:
      PASSWORD: "abc123."
    ports:
      - "10001:8888"
