version: "3"

networks:
    moodle_cocina-net:
        driver: bridge
services:
  mysql:
    image: mysql:5.7
    container_name: moodle_cocina-mysql
    tty: true
    ports:
      - "9004:3306"
    volumes:
      - "./var/lib/mysql/:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=moodle_cocina"
      - "MYSQL_USER=uadmin"
      - "MYSQL_PASSWORD=abc123."
    networks:
      - moodle_cocina-net
  moodle:
    image: bitnami/moodle:4.1.6
    container_name: moodle_cocina
    ports:
      - "9005:8080"
      #- "443:8443"  # Que pasará si descomentamos esta línea?
    volumes:
      - "./var/www/html/:/var/www/html"
      - "./var/www/moodledata:/bitnami/moodledata"
    environment:
      - "MOODLE_USERNAME=uadmin"
      - "MOODLE_PASSWORD=abc123."
      - "MOODLE_DATABASE_TYPE=mysqli"
      - "MOODLE_DATABASE_HOST=mysql"
      - "MOODLE_DATABASE_NAME=moodle_cocina"
      - "MOODLE_DATABASE_USER=uadmin"
      - "MOODLE_DATABASE_PASSWORD=abc123."
    depends_on:
      - mysql
    networks:
      - moodle_cocina-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: moodle_cocina-phpmyadmin
    ports:
      - "9006:80"
    environment:
      - "PMA_HOST=moodle_cocina-mysql"
      - "MYSQL_ROOT_PASSWORD=1234"
    depends_on:
      - mysql
    networks:
      - moodle_cocina-net