version: "3"

networks:
    moodle_cocina-net:
        driver: bridge
services:
  mysql:
    image: mysql:5.7
    container_name: moodle_cocina-mysql
    tty: true
    ports:
      - "9004:3306"
    volumes:
      - "./var/lib/mysql/:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=moodle"
      - "MYSQL_USER=uadmin"
      - "MYSQL_PASSWORD=abc123."
    networks:
      - moodle_cocina-net
  moodle:
    image: moodle:4.3
    container_name: moodle_cocina
    ports:
      - "9005:8080"
      #- "443:8443"  # Que pasará si descomentamos esta línea?
    volumes:
      - "./var/www/html/:/var/www/html"
      - "./var/www/moodledata:/var/www/moodledata"
    environment:
      - "MOODLE_DB_TYPE=mysql"
      - "MOODLE_DB_HOST=database"
      - "MOODLE_DB_PORT=3306"
      - "MOODLE_DB_NAME=moodle"
      - "MOODLE_DB_USER=uadmin"
      - "MOODLE_DB_PASSWORD=abc123."
    depends_on:
      - mysql
    networks:
      - moodle_cocina-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: moodle_cocina-phpmyadmin
    ports:
      - "9006:80"
    environment:
      - "PMA_HOST=moodle_cocina-mysql"
      - "MYSQL_ROOT_PASSWORD=1234"
    depends_on:
      - mysql
    networks:
      - moodle_cocina-net
